// File is autogenerated with `dub run libwasm:bootstrap-webpack`
import * as audio from './audio.js';
import * as bindings from './bindings.js';
import * as game from './game.js';
import * as spa from './spa.js';
import * as libwasm from './libwasm.js';
import * as webgl from './webgl.js';
const modules = [audio, bindings, game, spa, libwasm, webgl];
export { libwasm, modules }