// File is autogenerated with `dub run libwasm:bootstrap-webpack`
const abort = (what,file,line) => {
    throw `ABORT: $what @ $file:$line`;
}

const utf8Decoder = new TextDecoder('utf-8');
const utf8Encoder = new TextEncoder();

let objects = {1: document, 2: window};
let freelist = [];
let addObject = (value) => {
        if (value === null || value == undefined) return 0;
        let idx = freelist.pop() || ++libwasm.lastPtr;
        objects[idx] = value;
        return idx;
    },
    getObject = (ptr) => objects[ptr];
const setupMemory = (memory) => {
    libwasm.memory = memory;
    libwasm.buffer = memory.buffer;
}
const libwasm = {
    lastPtr: 2,
    instance: null,
    init: (modules) => {
        window.libwasm = libwasm
        if (!libwasm.exports) {
            var tmp = {};
            modules.map(m=>m.jsExports).filter(a=>!!a).map(e=>Object.entries(e).forEach(e=>tmp[e[0]] = Object.assign.apply(null,[tmp[e[0]] || {}, e[1]])));
            libwasm.exports = tmp;
        }
        if ('undefined' === typeof WebAssembly.instantiateStreaming) {
            fetch('underrun')
                .then(request => request.arrayBuffer())
                .then(bytes => WebAssembly.compile(bytes))
                .then(module => {
                    let instance = new WebAssembly.Instance(module, libwasm.exports);
                    libwasm.instance = instance
                    setupMemory(instance.exports.memory);
                    instance.exports._start(instance.exports.__heap_base);
                });
        } else {
            WebAssembly.instantiateStreaming(fetch('underrun'), libwasm.exports)
                .then(obj => {
                    let instance = obj.instance;
                    libwasm.instance = instance;
                    setupMemory(instance.exports.memory);
                    instance.exports._start(instance.exports.__heap_base);
                });
        }
    },
    objects,
    addObject: addObject,
}

let encoders = {
    string: (ptr, val) => {
        const encodedString = utf8Encoder.encode(val);
        const wasmPtr = libwasm.instance.exports.allocString(encodedString.length);
        const asBytes = new Uint8Array(libwasm.memory.buffer, wasmPtr, encodedString.length);
        const heapi32u = new Uint32Array(libwasm.memory.buffer)
        heapi32u[ptr / 4] = encodedString.length;
        heapi32u[(ptr / 4)+1] = wasmPtr;
        asBytes.set(encodedString);
        return ptr;
    }
}
let decoders = {
    string: (len, offset) => {
        if (offset == null) {
            const heapi32u = new Uint32Array(libwasm.memory.buffer)
            offset = heapi32u[(len+4)/4];
            len = heapi32u[(len/4)];
        }
        return utf8Decoder.decode(new DataView(libwasm.memory.buffer,offset,len));
    }
}
let jsExports = {
    env: {
        onOutOfMemoryError: () => abort("Out of memory exception"),
        _d_assert: (file,line) => abort("assert",file,line),
        doLog: arg => console.log(arg),
        memory: libwasm.memory,
        __assert: () => {},
        _Unwind_Resume: () => {
            console.log(arguments);
        },
        _d_dynamic_cast: () => {
            console.log(arguments)
        },
        libwasm_add__bool: (b)=>addObject(!!b),
        libwasm_add__int: addObject,
        libwasm_add__uint: addObject,
        libwasm_add__long: addObject,
        libwasm_add__ulong: addObject,
        libwasm_add__short: addObject,
        libwasm_add__ushort: addObject,
        libwasm_add__byte: addObject,
        libwasm_add__ubyte: addObject,
        libwasm_add__float: addObject,
        libwasm_add__double: addObject,
        libwasm_add__object: () => addObject({}),
        libwasm_add__string: (len, offset) => {
            return addObject(decoders.string(len, offset));
        },
        libwasm_get__field: (handle, len, offset) => {
            return addObject(getObject(handle)[decoders.string(len,offset)]);
        },
        libwasm_get__int: getObject,
        libwasm_get__uint: getObject,
        libwasm_get__long: getObject,
        libwasm_get__ulong: getObject,
        libwasm_get__short: getObject,
        libwasm_get__ushort: getObject,
        libwasm_get__float: getObject,
        libwasm_get__double: getObject,
        libwasm_get__byte: getObject,
        libwasm_get__ubyte: getObject,
        libwasm_get__string: (rawResult, ptr) => {
            encoders.string(rawResult, getObject(ptr));
        },
        libwasm_removeObject: (ctx) => {
            freelist.push(ctx)
            delete objects[ctx]
        },
        DataView_Create: (len, offset) => {
            return addObject(new DataView(libwasm.memory.buffer, offset, len));
        },
        Float32Array_Create: (len, offset) => {
            return addObject(new Float32Array(libwasm.memory.buffer, offset, len));
        },
        Uint8Array_Create: (len, offset) => {
            return addObject(new Uint8Array(libwasm.memory.buffer, offset, len));
        }
    }
};

export {libwasm, encoders, decoders, jsExports};
