// File is autogenerated with `dub run libwasm:bootstrap-webpack`
import * as libwasm from './libwasm.js';
import * as spa from './spa.js';
const modules = [libwasm, spa];
export {
    libwasm,
    modules
}
