// Isolated wasm conf for LDC 1.42.0 + libwasm/runtime-v1.42.0.
// Does not inherit stock import/ (would shadow CRuntime_LIBWASM object.d).
default:
{
    switches = [
        "-defaultlib=",
    ];
    post-switches = [
    ];
    lib-dirs = [
    ];
};

"^wasm(32|64)-":
{
    switches = [
        "-defaultlib=",
        "-d-version=CRuntime_LIBWASM",
        "-fno-moduleinfo",
        "-L-z",
        "-Lstack-size=1048576",
        "-L--stack-first",
        "-link-internally",
        "-L--export-dynamic",
    ];
    post-switches = [
        "-IE:\\cva6\\riscv-compilers\\libwasm\\runtime-v1.42.0",
    ];
    lib-dirs = [
    ];
};
