// Generated next to runtime-v<tag>. Use: ldc2 -conf=<this file>
default:
{
    switches = [ "-defaultlib=" ];
    post-switches = [];
    lib-dirs = [];
};
"^wasm(32|64)-":
{
    switches = [
        "-defaultlib=",
        "-d-version=CRuntime_LIBWASM",
        "-fno-moduleinfo",
        "-L-z", "-Lstack-size=1048576",
        "-L--stack-first",
        "-link-internally",
        "-L--export-dynamic",
    ];
    post-switches = [ "-IE:/cva6/riscv-compilers/libwasm/runtime-v1.43.0" ];
    lib-dirs = [];
};
