module generate;

import classify;
import kernel;
import parseutil;
import paths;
import walk;

import std.array : appender, join, replace, split;
import std.file : exists, mkdirRecurse, readText, write;
import std.format : format;
import std.path : buildPath, dirName;

struct GenerateStats
{
    int copiedLdc;
    int copiedLibwasm;
    int omitted;
    int jsWrote;
}

/// Rebuild a libwasm-compatible druntime/phobos tree from LDC 1.36 + current
/// adaptations. Identical files come from upstream; adapted/extra from libwasm;
/// missing kernel files stay omitted.
GenerateStats generateTree(const Inventory inv, string outDir)
{
    GenerateStats st;
    mkdirRecurse(outDir);
    mkdirRecurse(buildPath(outDir, "js"));

    auto manifest = appender!string();
    manifest.put("# Generated CRuntime_LIBWASM tree\n\n");
    manifest.put("Source: LDC v1.36.0 druntime/phobos + libwasm adaptations.\n");
    manifest.put("Tool: tools/runtime-adapt (libdparse / serve-d parser).\n\n");
    manifest.put("| path | action | kind | group | note |\n");
    manifest.put("|---|---|---|---|---|\n");

    foreach (r; inv.rows)
    {
        manifest.put(format("| `%s` | %s | %s | %s | %s |\n",
            r.rel, r.action, kindName(r.kind), groupName(r.group),
            r.note.replace("|", "/")));

        if (r.action == "omit")
        {
            st.omitted++;
            continue;
        }
        string src;
        if (r.action == "copy-ldc")
            src = r.ldcPath;
        else
            src = r.oursPath;
        if (!src.length || !exists(src))
            continue;
        auto dest = buildPath(outDir ~ r.rel.split("/"));
        mkdirRecurse(dirName(dest));
        auto text = normalizeSource(readText(src));
        write(dest, text);
        if (r.action == "copy-ldc")
            st.copiedLdc++;
        else
            st.copiedLibwasm++;
    }

    write(buildPath(outDir, "MANIFEST.md"), manifest.data);
    writeJsEhStubs(buildPath(outDir, "js", "error-handling.ts"));
    writeJsEhStubs(buildPath(outDir, "js", "error-handling.js.txt"));
    st.jsWrote = 2;
    write(buildPath(outDir, "js", "README.md"), jsReadme());
    return st;
}

void writeJsEhStubs(string dest)
{
    write(dest, jsEhStubsSource());
}

/// Assert-shaped JS error handling for current LDC 1.36 (`captureException`)
/// and newest-LDC wasm-eh (`_Unwind_Resume`, optional tag). Same ABI as
/// `onAssertErrorMsg`: length+ptr pairs into linear memory, then abort.
string jsEhStubsSource()
{
    return q"JS
// Generated by libwasm tools/runtime-adapt.
// Error handling mirrors onAssertErrorMsg: decode D strings from WASM
// linear memory, then abort. Do not swallow exceptions (the previous
// captureException only console.log'd).
//
// Wire these into jsExports.env next to the existing assert import.
// wasm-eh (newest LDC + --wasm-enable-eh -mattr=+exception-handling)
// still calls _d_throw_exception from the LDC frontend (DtoThrow);
// the implementation may be a JS import (today) or a wasm `throw` to
// a tag that JS catches as WebAssembly.Exception.

export function installErrorHandling(env, decoders, abort) {
  const decode = (len, ptr) => {
    if (typeof len === 'string') return len; // old dom-ts ABI
    return decoders.string(len, ptr);
  };

  env.onAssertErrorMsg = (fileLen, filePtr, line, msgLen, msgPtr) => {
    abort('assert', decode(fileLen, filePtr), line, decode(msgLen, msgPtr));
  };

  env.onUnittestErrorMsg = (fileLen, filePtr, line, msgLen, msgPtr) => {
    abort('unittest', decode(fileLen, filePtr), line, decode(msgLen, msgPtr));
  };

  // Current libwasm.rt.stubs._d_throw_exception → captureException(string).
  // Same shape as onAssertErrorMsg (D string = length + ptr).
  env.captureException = (msgLen, msgPtr) => {
    const msg = decode(msgLen, msgPtr);
    abort('exception', '', 0, msg);
  };

  // Newest-LDC wasm-eh leftovers. Keep no-op-or-abort, never silent.
  env._Unwind_Resume = () => abort('unwind', '', 0, '_Unwind_Resume');
  env._d_delThrowable = () => {};
  env.__cxa_begin_catch = (ptr) => ptr;
  env.__cxa_end_catch = () => {};
  env.__cxa_rethrow = () => abort('exception', '', 0, '__cxa_rethrow');

  return env;
}
JS";
}

string jsReadme()
{
    return q"MD
# JS error-handling stubs

`onAssertErrorMsg` is the model: D passes a file/line/msg, JS aborts.

`captureException` (today) and any wasm-eh landing-pad import must do the
same, not `console.log` and continue. Binaryen `--asyncify` plus LLVM 17
`--wasm-enable-eh` composition is still unverified; aborting is the safe
host policy until catch works.

See libwasm `architecture/js-events-memory.md` and `upgrade-ldc.md`.
MD";
}
