module report;

import classify;
import kernel;
import parseutil;
import walk;

import std.algorithm : map, sort;
import std.array : appender, array, join;
import std.conv : to;
import std.format : format;
import std.json;

string renderMarkdown(const Inventory inv, const UpgradeRow[] upgrade,
    string ldcRoot, string libwasmRoot, string newImport)
{
    auto c = countKinds(inv.rows);
    auto buf = appender!string();
    buf.put("# libwasm runtime vs LDC 1.36.0\n\n");
    buf.put("Generated by `tools/runtime-adapt` using **libdparse** ");
    buf.put("(the parser serve-d / D-Scanner load).\n\n");
    buf.put(format("- LDC root: `%s`\n", ldcRoot));
    buf.put(format("- libwasm: `%s`\n", libwasmRoot));
    if (newImport.length)
        buf.put(format("- newest import/: `%s`\n", newImport));
    buf.put("\n## Counts\n\n");
    buf.put("| kind | n | generate action |\n|---|---:|---|\n");
    buf.put(format("| identical | %s | copy from LDC 1.36 |\n", c.identical));
    buf.put(format("| adapted | %s | copy from libwasm |\n", c.adapted));
    buf.put(format("| stub-adapt | %s | copy from libwasm |\n", c.stubAdapt));
    buf.put(format("| extra | %s | copy from libwasm |\n", c.extra));
    buf.put(format("| missing | %s | omit (kernel / unported) |\n", c.missing));
    buf.put(format("| **total** | **%s** | |\n\n", inv.rows.length));

    buf.put("## Kernel groups (why stubs were required)\n\n");
    buf.put("| group | missing | adapted | identical | extra | rationale |\n");
    buf.put("|---|---:|---:|---:|---:|---|\n");
    foreach (g; countGroups(inv.rows))
    {
        if (g.missing + g.adapted + g.identical + g.extra == 0)
            continue;
        buf.put(format("| %s | %s | %s | %s | %s | %s |\n",
            groupName(g.group), g.missing, g.adapted, g.identical, g.extra,
            omitRationale(g.group)));
    }

    buf.put("\n## D replacements in `source/libwasm/rt`\n\n");
    foreach (k; inv.kernelRt)
        buf.put(format("- `%s`\n", k.rel));
    buf.put("\nSymbols: ");
    buf.put(dKernelReplacements.join(", "));
    buf.put("\n\n## JS kernel stubs (`env`)\n\n");
    buf.put("| import | role |\n|---|---|\n");
    foreach (s; jsKernelStubs)
        buf.put(format("| `%s` | %s |\n", s.name, s.role));

    buf.put("\n## Adapted / stub-adapt files\n\n");
    buf.put("| path | kind | ldc B | ours B | parsed | note |\n|---|---|---:|---:|---|---|\n");
    foreach (r; inv.rows)
    {
        if (r.kind != Kind.adapted && r.kind != Kind.stubAdapt)
            continue;
        buf.put(format("| `%s` | %s | %s | %s | %s/%s | %s |\n",
            r.rel, kindName(r.kind), r.ldcBytes, r.oursBytes,
            r.ldcParse.parsed ? "ok" : "fail",
            r.oursParse.parsed ? "ok" : "fail", r.note));
    }

    buf.put("\n## Extra (libwasm-only)\n\n");
    foreach (r; inv.rows)
        if (r.kind == Kind.extra)
            buf.put(format("- `%s` — %s\n", r.rel, r.note));

    buf.put("\n## Missing CTFE-keep (should port or stub)\n\n");
    auto ctfeMiss = missingByGroup(inv.rows, KernelGroup.ctfeKeep);
    if (!ctfeMiss.length)
        buf.put("(none)\n");
    else
        foreach (m; ctfeMiss)
            buf.put(format("- `%s`\n", m));

    buf.put("\n## Missing phobos-math (current build break)\n\n");
    foreach (m; missingByGroup(inv.rows, KernelGroup.phobosMath))
        buf.put(format("- `%s`\n", m));

    if (upgrade.length)
    {
        buf.put("\n## Upgrade map → newest LDC import/\n\n");
        int[string] vc;
        foreach (u; upgrade)
            vc[u.verdict] = vc.get(u.verdict, 0) + 1;
        buf.put("| verdict | n |\n|---|---:|\n");
        auto ks = vc.byKey.array;
        ks.sort;
        foreach (k; ks)
            buf.put(format("| %s | %s |\n", k, vc[k]));
        buf.put("\nReapply / stub-or-port (first 80):\n\n");
        int n;
        foreach (u; upgrade)
        {
            if (u.verdict != "reapply-adapt" && u.verdict != "stub-or-port")
                continue;
            buf.put(format("- `%s` — **%s** — %s\n", u.rel, u.verdict, u.note));
            if (++n >= 80)
            {
                buf.put("\n_(truncated)_\n");
                break;
            }
        }
    }

    if (inv.parseFailures.length)
    {
        buf.put("\n## Parse failures (libdparse)\n\n");
        foreach (e; inv.parseFailures)
            buf.put("- " ~ e ~ "\n");
    }
    return buf.data;
}

string renderJson(const Inventory inv, const UpgradeRow[] upgrade)
{
    JSONValue root;
    auto c = countKinds(inv.rows);
    root["counts"] = JSONValue([
        "identical": JSONValue(c.identical),
        "adapted": JSONValue(c.adapted),
        "stubAdapt": JSONValue(c.stubAdapt),
        "extra": JSONValue(c.extra),
        "missing": JSONValue(c.missing),
        "total": JSONValue(cast(int) inv.rows.length),
    ]);
    JSONValue[] files;
    foreach (r; inv.rows)
    {
        JSONValue j;
        j["rel"] = r.rel;
        j["kind"] = kindName(r.kind);
        j["group"] = groupName(r.group);
        j["action"] = r.action;
        j["note"] = r.note;
        j["ldcBytes"] = r.ldcBytes;
        j["oursBytes"] = r.oursBytes;
        files ~= j;
    }
    root["files"] = JSONValue(files);
    JSONValue[] up;
    foreach (u; upgrade)
    {
        JSONValue j;
        j["rel"] = u.rel;
        j["verdict"] = u.verdict;
        j["note"] = u.note;
        up ~= j;
    }
    root["upgrade"] = JSONValue(up);
    JSONValue[] js;
    foreach (s; jsKernelStubs)
    {
        JSONValue j;
        j["name"] = s.name;
        j["role"] = s.role;
        js ~= j;
    }
    root["jsStubs"] = JSONValue(js);
    return root.toPrettyString;
}
