// File is autogenerated with `dub run libwasm:bootstrap-webpack`
import * as bindings from './bindings.js';
import * as spa from './spa.js';
import * as libwasm from './libwasm.js';
const modules = [bindings, spa, libwasm];
export { libwasm, modules }