// File is autogenerated with `dub run libwasm:bootstrap-webpack`
import * as bindings from './bindings.ts';
import * as spa from './spa.ts';
import * as libwasm from './libwasm.ts';
const modules = [bindings, spa, libwasm];
export { libwasm, modules }