// File is autogenerated with `dub libwasm:webidl -- --bindgen`
import {libwasm as spa, encoders as encoder, decoders as decoder} from '../modules/libwasm.js';
let libwasm = spa;
let memory = {};
const setupMemory = () => {
    let buffer = libwasm.memory.buffer;
    if (memory.heapi32s && !memory.heapi32s.length === 0)
        return;
    memory.heapi32s = new Int32Array(buffer)
    memory.heapi32u = new Uint32Array(buffer)
    memory.heapi16s = new Int16Array(buffer)
    memory.heapi16u = new Uint16Array(buffer)
    memory.heapi8s = new Int8Array(buffer)
    memory.heapi8u = new Uint8Array(buffer)
    memory.heapf32 = new Float32Array(buffer)
    memory.heapf64 = new Float64Array(buffer)
}
const setBool = (ptr, val) => (memory.heapi32u[ptr/4] = +val),
      setInt = (ptr, val) => (memory.heapi32s[ptr/4] = val),
      setUInt = (ptr, val) => (memory.heapi32u[ptr/4] = val),
      setShort = (ptr, val) => (memory.heapi16s[ptr/2] = val),
      setUShort = (ptr, val) => (memory.heapi16u[ptr/2] = val),
      setByte = (ptr, val) => (memory.heapi8s[ptr] = val),
      setUByte = (ptr, val) => (memory.heapi8u[ptr] = val),
      setFloat = (ptr, val) => (memory.heapf32[ptr/4] = val),
      setDouble = (ptr, val) => (memory.heapf64[ptr/8] = val),
      getBool = (ptr) => memory.heapi32u[ptr/4],
      getInt = (ptr) => memory.heapi32s[ptr/4],
      getUInt = (ptr) => memory.heapi32u[ptr/4],
      getShort = (ptr) => memory.heapi16s[ptr/2],
      getUShort = (ptr) => memory.heapi16u[ptr/2],
      getByte = (ptr) => memory.heapi8s[ptr],
      getUByte = (ptr) => memory.heapi8u[ptr],
      getFloat = (ptr) => memory.heapf32[ptr/4],
      getDouble = (ptr) => memory.heapf64[ptr/8],
      isDefined = (val) => (val != undefined && val != null),
      encode_handle = (ptr, val) => { setUInt(ptr, libwasm.addObject(val)); },
      decode_handle = (ptr) => { return libwasm.objects[getUInt(ptr)]; },
      libwasm_encode_string = encoder.string,
      libwasm_decode_string = decoder.string,
      libwasm_indirect_function_get = (ptr)=>libwasm.instance.exports.__indirect_function_table.get(ptr),
  libwasm_decode_Handle = decode_handle,
  libwasm_decode_RequestInfo = (ptr)=>{
    return libwasm_decode_union2_Request_string(ptr);
  },
  libwasm_decode_union2_Request_string = (ptr)=>{
    if (getUInt(ptr) == 0) {
      return libwasm_decode_Handle(ptr+4);
    } else if (getUInt(ptr) == 1) {
      return libwasm_decode_string(ptr+4);
    }
  };
export let jsExports = {
  env: {
    Body_json: (ctx) => {
      setupMemory();
      return libwasm.addObject(libwasm.objects[ctx].json());
    },
    WindowOrWorkerGlobalScope_fetch_0: (ctx, input) => {
      setupMemory();
      return libwasm.addObject(libwasm.objects[ctx].fetch(libwasm_decode_RequestInfo(input)));
    },
    console_log: (data) => {
      setupMemory();
      console.log(libwasm.objects[data]);
    },
    promise_then_6uhandlehandle: (handle, ctx, ptr) => {
      return libwasm.addObject(libwasm.objects[handle].then((r)=>{
        encode_handle(0,r);
        libwasm_indirect_function_get(ptr)(512, ctx, 0);
        return decode_handle(512);
      }));
    },
    promise_then_6uhandlev: (handle, ctx, ptr) => {
      return libwasm.addObject(libwasm.objects[handle].then((r)=>{
        encode_handle(0,r);
        libwasm_indirect_function_get(ptr)(ctx, 0);
      }));
    },
  }
}