// File is autogenerated with `dub run libwasm:webidl -- --bindgen`
import * as spa from './spa.js';
import * as libwasm from './libwasm.js';
import * as bindings from './bindings.js';
const modules = [spa, libwasm, bindings];
export { libwasm, modules }